version: '3'

services:
  db:
    image: mysql:8
    restart: always
    user: 1000:1000
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./vol/mysql_data:/var/lib/mysql
    env_file: ${ENV}.env
    security_opt:
      - seccomp:unconfined

  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: wsgi
    ports:
      - 8080:8080
    restart: on-failure
    env_file: ${ENV}.env
    depends_on:
      - db
