version: '3'

services:
  web:
    build:
      dockerfile: deploy/Dockerfile
      context: ..
    command: wsgi
    volumes:
      - ./vol/sqlite.db:/tmp/sqlite.db
    ports:
      - 8080:8080
    restart: on-failure
    env_file: ${ENV}.env
